version: '3'

services: 

    #Backend api
    crowndfunding-backend-api:
        container_name: crowndfunding-backend
        working_dir: /usr/src/crowdfunding/backend/
        build: ./
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/crowndfunding/backend/
        links: 
            - mongodb
    
    #mongodb
    mongodb:
        image: mongo
        ports: 
            - "27017:27017"
